### ISSUE TITLE
Where is the CMakeLists.txt file?

### ISSUE THREAD

**Issue by Elhison** [tostc/libDiscordBot#1]
`D3CRYPT3D:build CottonTheButton$ cmake ../
CMake Error: The source directory "/Users/icebunny08/libDiscordBot" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.`

**Comment by tostc** [comment]
Hi,

maybe you are not on the right branch, because the master branch doesn't have any source yet. But if you want to checkout the current development status you must call
`git checkout development` inside the library directory. You need also to create a folder inside the library directory which called 'externals'. After that you need to download all the libraries which are listed in the README.MD. But I don't know if the library will successfully build, because this library is work in progress. I think I will release the first alpha version of this library, at this weekend, in the master branch, which will setup most of the libraries automatically.
